# sudo docker compose up -d
#
# To connect to postgres instance from host:
#   psql -U postgres -h <host ip>

# From grafana docker docs
#Note: Though both methods are similar, there is a slight difference. 
#If you want your storage to be fully managed by Docker and accessed 
#only through Docker containers and the Docker CLI, you should choose 
#to use persistent storage. However, if you need full control of 
#the storage and want to allow other processes besides Docker to access
# or modify the storage layer, then bind mounts is the right choice for
# your environment.

version: "3.8"

services:
  # postgresql:
  #   image: postgres:14.9
  #   container_name: postgresql
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

  # timescaledb:
  #   image: timescale/timescaledb-ha:pg14-latest
  #   container_name: timescaledb
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - timescale-data:/home/postgres/pgdata/data

  # grafana:
  #   image: grafana/grafana-enterprise
  #   container_name: grafana
  #   restart: always
  #   user: '0' # necessary is using bing mounts for persistance
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     # - grafana-data:/var/lib/grafana # using docker volume
  #     - './grafana-mount:/var/lib/grafana' # using bind mount

  # gitlab:
  #   image: 'gitlab/gitlab-ce:latest'
  #   container_name: gitlab
  #   restart: always
  #   hostname: 'gitlab-test.com'
  #   # environment:
  #   # https://stackoverflow.com/questions/70139731/docker-compose-yml-with-gitlab-omnibus-config-not-working
  #   # GITLAB_OMNIBUS_CONFIG: |
  #   #     external_url 'http://gitlab-test.com'
  #   ports:
  #     - '8080:80'
  #     - '4433:443'
  #     - '2222:22'
  #   volumes:
  #     - '/home/jamie/Desktop/docker/gitlab-mount/config:/etc/gitlab'
  #     - '/home/jamie/Desktop/docker/gitlab-mount/logs:/var/log/gitlab'
  #     - '/home/jamie/Desktop/docker/gitlab-mount/app-data:/var/opt/gitlab'

  vernemq:
    image: vernemq/vernemq
    container_name: vernemq
    restart: always
    environment:
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
    ports:
      - '1883:1883'

    



volumes:
  postgres-data:
  timescale-data:
  grafana-data:
    # driver: local
    # external: true
    # driver_opts:
      # o: 'bind'
      # device: 